import { StyleSheet } from "react-native";
export default StyleSheet.create({
  row: {
    flexDirection: "row",
  },
  background: {
    flex: 1,
    backgroundColor: "#F2F2F7",
  },
  container: {
    flex: 1,
    backgroundColor: "#F2F2F7",
  },
  inputView: {
    padding: 16,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
  },
  view: {
    flex: 1,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  input: {
    flex: 1,
    padding: 16,
    margin: 4,
    borderRadius: 25,
    outline: "none",
    borderColor: "transparent",
    backgroundColor: "#F2F2F7",
    fontSize: 16,
    maxHeight: 100,
  },

  sendView: {
    padding: 8,
    minHeight: 45,
    maxHeight: 200,
    width: "100%",
    alignItems: "flex-end",
    marginVertical: 4,
    marginHorizontal: 16,
  },
  receivedView: {
    width: "100%",
    alignItems: "flex-start",
    marginVertical: 4,
    marginHorizontal: 16,
  },
  sendText: {
    backgroundColor: "#007AFF",
    color: "white",
    borderRadius: 20,
    maxWidth: "75%",
    padding: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    lineHeight: 20,
    shadowColor: "#007AFF",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  receivedText: {
    backgroundColor: "white",
    color: "#1C1C1E",
    borderRadius: 20,
    maxWidth: "75%",
    padding: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    lineHeight: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  metaDataView: {
    flexDirection: "row",
    marginTop: 4,
    marginHorizontal: 16,
  },
  metaDataText: {
    marginHorizontal: 4,
    fontSize: 12,
    color: "#8E8E93",
  },
});
