/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/style` | `/style`; params?: Router.UnknownInputParams; } | { pathname: `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `/connexion/inscription`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | { pathname: `/room/roomBox`; params?: Router.UnknownInputParams; } | { pathname: `/utils/requete`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/style` | `/style`; params?: Router.UnknownOutputParams; } | { pathname: `/connexion`; params?: Router.UnknownOutputParams; } | { pathname: `/connexion/inscription`; params?: Router.UnknownOutputParams; } | { pathname: `/room`; params?: Router.UnknownOutputParams; } | { pathname: `/room/roomBox`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/requete`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/style${`?${string}` | `#${string}` | ''}` | `/style${`?${string}` | `#${string}` | ''}` | `/connexion${`?${string}` | `#${string}` | ''}` | `/connexion/inscription${`?${string}` | `#${string}` | ''}` | `/room${`?${string}` | `#${string}` | ''}` | `/room/roomBox${`?${string}` | `#${string}` | ''}` | `/utils/requete${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/style` | `/style`; params?: Router.UnknownInputParams; } | { pathname: `/connexion`; params?: Router.UnknownInputParams; } | { pathname: `/connexion/inscription`; params?: Router.UnknownInputParams; } | { pathname: `/room`; params?: Router.UnknownInputParams; } | { pathname: `/room/roomBox`; params?: Router.UnknownInputParams; } | { pathname: `/utils/requete`; params?: Router.UnknownInputParams; };
    }
  }
}
